Build 1894
v1.32.0.1894 Updates & Fixes

!! You have to update ValorlessUtils to v1.12.0.262, in order for this update to work.

Added: Support for the new ItemModel, while keeping CustomModelData support.
Simply change the CustomModelData value, to that of the ItemModel, like so:
https://i.gyazo.com/427b134136c01e94cce8e768467896e9.png

Added: Weight of items in the bag is now shown on item tooltips, if ProtocolLib is present on the server, and weight is enabled.
Config entry "weight-tooltip" added to weight.yml.

Added: You can now define how many bags a player can carry at a time.
The new config setting "carry-limit" is defaulted to 0, to not affect your current setup :)
In addition, if you want to set the carry limit per rank, you can give the new permission "havenbags.carry.X" to set their limit.

Added: Bags can no longer be opened while the database is loading.
Should you force reload, or a player happens to try and open while restarting the plugin.
Just extra safety.

Changed: Reworked how bag creations and opening is handled.
Using an uncreated bag will now create, update and open it.
This should help not accidentally giving out already used bags.

Changed: PvPManager: Regardless of the player's pvp status, players can now use their bags if pvp is disabled globally. (/pvpglobal <on|off>)

Changed: Items that can't go into bags, can now be picked up to move around, but still can't go into bags.

Changed: Bags can no longer be dropped if they're open. Oops

Fixed: Potential fix for the following error.
Could not pass event InventoryCloseEvent to HavenBags v1.31.2.xxxx
java.lang.NullPointerException: ItemStack can't be null/air/amount of 0! This is not a NBTAPI bug!

Fixed: An issue on 1.20.5+, causing some items to not appear in the bag's lore.
The code was set up wrong, causing some items to be skipped.

Fixed: An issue where bags weren't removed entirely, when deleting bags through the admin gui.

Internal: Marked datamodel ActiveBag.java as deprecated.
Has been replaced by functions in BagData.
Mainly BagData.IsBagOpen() and BagData.GetOpenBags().