Build 1535
v1.21.1.1535 Minecraft 1.21.1 & Hotfixes

You have to update ValorlessUtils to v1.8.1.237, in order for this update to work.

Added: Minecraft 1.21.1 support.

Fixed: plugins.yml now correcly reloads with the command '/havenbags reload'.

Fixed: The following error when a non-upgrade token is put in the anvil alongside the bag.
[code=yml]Could not pass event PrepareAnvilEvent to HavenBags v1.21.0.1531
java.lang.IllegalStateException: We don't have CustomModelData! Check hasCustomModelData first![/code]